### ISSUE TITLE
TODO, DOING, DONE 영역별 UI 구현

### ISSUE THREAD

**Issue by innieminnie** [innieminnie/ios-project-manager#4]
- [x] 영역별 CollectionView의 cell UI요소 배치하기
- [x] 드래그 앤 드롭을 통한 cell 위치 변경 구현
- [x] cell 탭했을 때, modal로 할 일 상세보기 기능 구현
- [x] 할 일 상세보기 화면에서 edit 버튼 탭했을 때, 할 일 수정하기 화면 구현
- [x] swipe시 할 일 삭제 UI 구현
